// <auto-generated />
namespace MateuszBartkowiakHomework4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Addlistoffilms : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addlistoffilms));
        
        string IMigrationMetadata.Id
        {
            get { return "201912131436420_Add list of films"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
