// <auto-generated />
namespace MateuszBartkowiakHomework4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class ChangetypeofRow : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangetypeofRow));
        
        string IMigrationMetadata.Id
        {
            get { return "201912131838306_Change type of Row"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
